import art from "./art.webp"
import art_links from "./art-links.webp"
import blog from "./blog-1.webp"
import clock from "./clock.webp"
import dice from "./dice.webp"
import flashcards from "./flashcards.webp"
import employee from "./employee.webp"
import family from "./family.webp"
import flex_cv from "./flex-cv.webp"
import high_five from "./high-five.webp"
import hookd from "./hookd.webp"
import memory from "./memory.webp"
import parallax from "./parallax.webp"
import portfolio_retro from "./portfolio-retro.webp"
import star_squid from "./star-squid.webp"

export {star_squid, portfolio_retro, parallax, memory, hookd, high_five, flex_cv, family, employee, flashcards, dice, clock, blog, art, art_links}